### PR TITLE
Website on Github pages

### PR DESCRIPTION
**Pull request by rooose**
Hi! I noticed the radio was not working, so I made (if you want it) a version that is deployable on Github Pages (so that its less annoying to manage) :)

Changes:
- All the songs scripts (.py) are now in the folder ./songs_scripts/ (I did not delete any of them, even if Github seems to think so 🤔)
- I fixed some errors in some song scripts that were preventing them from compiling
- I put the main code under `if __name__ == '__main__'` clause to be able to import the information without running the script
- I changed the template as well to have the `name == main` check

- All the generated songs (.ogg) are in the folder ./songs/ (It is where the app reads the assets to play them)
- I created the script `generate_ogg.py` which generates all the songs in the ogg format and the metadata file that contains all the information for the website

- I created a github workflow that will generate the new songs everytime someone pushes on the main branch (so, if someone wants to propose a song, they can open a PR, and when it is accepted and pushed, their song will automatically be generated in the .ogg format). It will automatically add it to the website as well :)

- In `radio_pyo.py`:
- I added an argparser instead of reading straight up from the sysargs
- I changed the basepath to be local to the git repository
- I changed the get_song_info to get the information by 'importing' the file instead of parsing it
- I added typing for clarity

The website is hosted on my github pages as a demo for now (https://rooose.github.io/radiopyo/) 
image

Hope you like it :)

### CODE REVIEW

**Comment by tiagovaz** [comment]
Wow, that's just amazing, what a lovely work! I'm merging your PR and if you intend to do some more work on this repo in the future I'd be happy to add you as contributor right now. Thanks!

**Comment by rooose** [comment]
Hi! That would be aswesome :) I'd be able to setup the github pages to host it from your repo, and I wanted to add look into adding a previous song button 😁

**Comment by tiagovaz** [comment]
Yes yes, please. Then I'll set the 'official' domain .acaia.ca to it and announce to pyo mailing list. Thanks!

**Comment by rooose** [comment]
You need to be the owner of the repository to do it, so here's a quick tutorial if you need! https://www.codecademy.com/articles/f1-u3-github-pages

Bascially just go to settings, in options, there is a 'Github Pages' section, just select the root branch like so: 
image
and it should work 😊 You can even set the officiel domain name over there I think!

**Comment by tiagovaz** [comment]
Nice, done. I'll set the domain as well. Meanwhile it's already pointing to your instance if you don't mind :-)

**Comment by tiagovaz** [comment]
Hello again @rooose, I'm not used to gh workflows, so I'm wondering if would be possible to regenerate each song after it being streamed rather than for each new commit.
Those compositions have random sections, and that's the main point of the radio: songs never play twice in the same way!
For instance, the old script created a stamp file for the song as soon as it was selected to be streamed, and another script running in a loop would look for stamp files and regenerate those 'stamped' (that could be done in a cronjob as well). Anyway, let me know if you can see any solution for this on the new workflow, merci!

**Comment by rooose** [comment]
Hi! Hmm, I have a few guesses on how to do this, but I'll investigate a bit. I'll try to recreate the stamp mechanism, and if it doesn't work I'll setup something else! For now I can setup a cronjob on github actions so that it's at least a bit random :)

**Pull request merged**
